apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-container
          image: influxdb-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /ping
              port: 8086
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb
            - name: influxdb-conf
              subPath: influxdb.conf
              mountPath: /etc/influxdb/influxdb.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: influxdb-secret
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: influxdb-conf
          configMap:
            name: influxdb-config