apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana-container
          image: grafana-image
          imagePullPolicy: Never
          volumeMounts:
            - name: grafana-data
              subPath: grafana.ini
              mountPath: /etc/grafana/grafana.ini
              readOnly: true
      volumes:
        - name: grafana-data
          configMap:
            name: grafana-config